2024-11-29 09:18:05,409 - INFO - Exceção durante conexão: socket is already closed.
2024-11-29 09:18:07,348 - ERROR - Exceção durante conexão: Traceback (most recent call last):
  File "/Users/thiagosotero/Documents/calculadora_martingale/bot-gui.py", line 212, in conectar
    self.api.alterar_tipo_conta(self.TIPO_CONTA)
  File "/Users/thiagosotero/Documents/calculadora_martingale/bot-gui.py", line 32, in alterar_tipo_conta
    self.iq.change_balance(tipo_conta)
  File "/opt/anaconda3/lib/python3.12/site-packages/iqoptionapi/stable_api.py", line 496, in change_balance
    set_id(real_id)
  File "/opt/anaconda3/lib/python3.12/site-packages/iqoptionapi/stable_api.py", line 475, in set_id
    self.position_change_all(
  File "/opt/anaconda3/lib/python3.12/site-packages/iqoptionapi/stable_api.py", line 462, in position_change_all
    self.api.portfolio(Main_Name=Main_Name, name="portfolio.position-changed",
  File "/opt/anaconda3/lib/python3.12/site-packages/iqoptionapi/api.py", line 538, in portfolio
    self.send_websocket_request(
  File "/opt/anaconda3/lib/python3.12/site-packages/iqoptionapi/api.py", line 277, in send_websocket_request
    self.websocket.send(data)
  File "/opt/anaconda3/lib/python3.12/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/websocket/_socket.py", line 135, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

